version: '3'
services:
    api:
        build:
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - '3050:80'
        command: ["npm", "run", "dev"]